### ISSUE TITLE
Site section and Topic facet issue

### ISSUE THREAD

**Issue by nichgray** [CDRH/bandhistory_rails#34]
Punctuation is being stripped out of the site section and topic facets in the upgraded version.

 
<img width="291" alt="Screenshot 2024-11-25 at 4 12 34 PM" src="https://github.com/user-attachments/assets/ea437399-a088-4f0d-985b-1386e9c836f8">

**Comment by wkdewey** [comment]
<img width="226" alt="Screenshot 2024-12-19 at 4 01 16 PM" src="https://github.com/user-attachments/assets/30804356-1413-4c7f-8230-60dea8ee8fc0" />
I think this is fixed now with Orchid/API updates
